name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  start-backend-app:

    runs-on: ubuntu-latest
    environment: workflow test
    steps:    
    - name: Checkout Branch
      uses: actions/checkout@v3
    
    - name: Create .env file
      
      uses: SpicyPizza/create-envfile@v1.3.0
      with:
        envkey_AWS_REGION: ${{ secrets.AWS_REGION }}
        envkey_USER_POOL: ${{ secrets.USER_POOL }}
        envkey_USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
        envkey_USER_POOL_SECRET: ${{ secrets.USER_POOL_SECRET }}
        envkey_ADMIN_POOL: ${{ secrets.ADMIN_POOL }}
        envkey_ADMIN_POOL_ID: ${{ secrets.ADMIN_POOL_ID }}
        envkey_ADMIN_POOL_SECRET: ${{ secrets.ADMIN_POOL_SECRET }}
        directory: FlexiCharge-Backend/backend-app/
